export type Destination = {
  slug: string;
  name: string;
  country: string;
  region: string;
  duration: string;
  price: string;
  priceLabel: string;
  heroImage: string;
  description: string;
  longDescription: string;
  highlights: string[];
  tips: string[];
  bestTime: string;
  metaTitle: string;
  metaDescription: string;
  keywords: string[];
  lat: number;
  lng: number;
};

export const destinations: Destination[] = [
  {
    slug: "monaco",
    name: "Monaco & Monte-Carlo",
    country: "Monaco",
    region: "Principauté de Monaco",
    duration: "30 min de Nice",
    price: "90",
    priceLabel: "À partir de 90€",
    heroImage: "https://images.unsplash.com/photo-1527004013197-933c4bb611b3?auto=format&fit=crop&w=1920&q=85",
    description: "Découvrez la Principauté en toute exclusivité avec votre chauffeur privé Riviora.",
    longDescription: `Monaco, joyau de la Méditerranée niché entre mer et montagne, est l'une des destinations les plus glamour au monde. En seulement 30 minutes depuis Nice, votre chauffeur Riviora vous transporte dans cet État indépendant où luxe, discrétion et excellence se conjuguent au quotidien.\n\nLe Casino de Monte-Carlo, chef-d'œuvre Belle Époque, le Palais du Prince qui domine le Rocher, le Musée Océanographique fondé par le Prince Albert Ier, le circuit de Formule 1 légendaire, les jardins exotiques suspendus… Chaque coin de Monaco recèle une histoire extraordinaire que votre chauffeur-guide vous révèlera avec passion.\n\nRiviora vous propose des excursions personnalisées à Monaco : demi-journée découverte, journée complète ou simple transfert depuis l'aéroport de Nice. Nous adaptons l'itinéraire à vos envies : shopping au Métropole, déjeuner en terrasse vue mer, visite des jardins ou simple balade sur le port des yachts.`,
    highlights: ["Casino de Monte-Carlo", "Palais du Prince & Changing of the Guard", "Musée Océanographique", "Port Hercule & ses superyachts", "Jardins Exotiques", "Circuit F1 Grand Prix", "Le Rocher & Monaco-Ville"],
    tips: ["Évitez les week-ends de Grand Prix (mai) — préférez les jours de semaine", "Le Musée Océanographique ouvre à 10h — arrivez tôt pour éviter les files", "Le quartier de Fontvieille est calme et authentique, loin des touristes"],
    bestTime: "Avril–Juin et Septembre–Octobre",
    metaTitle: "Excursion Monaco en voiture privée depuis Nice | Riviora",
    metaDescription: "Excursion Monaco & Monte-Carlo depuis Nice avec chauffeur privé. Casino, Palais du Prince, Musée Océanographique. Dès 90€. Réservez Riviora.",
    keywords: ["excursion Monaco", "chauffeur privé Monaco", "VTC Nice Monaco", "visite Monte-Carlo", "transfert Nice Monaco"],
    lat: 43.7384,
    lng: 7.4246,
  },
  {
    slug: "saint-tropez",
    name: "Saint-Tropez",
    country: "France",
    region: "Var, Provence",
    duration: "1h30 de Nice",
    price: "350",
    priceLabel: "À partir de 350€",
    heroImage: "https://images.unsplash.com/photo-1622547748225-3fc4abd2cca0?auto=format&fit=crop&w=1920&q=85",
    description: "Le glamour de la Côte d'Azur authentique, ses plages de légende et ses ruelles médiévales.",
    longDescription: `Saint-Tropez, rendu célèbre par Brigitte Bardot dans les années 60, reste l'une des destinations les plus mythiques de la Côte d'Azur. Village de pêcheurs devenu capitale mondiale du glamour, Saint-Tropez séduit par son authenticité préservée et son atmosphère unique.\n\nVotre chauffeur Riviora vous conduit en toute sérénité depuis Nice ou Cannes, sans le stress du stationnement impossible pendant la haute saison. Une fois sur place, découvrez la Place des Lices et son marché provençal le mardi et samedi, le Port de plaisance animé par les yachts des célébrités, la Citadelle du XVIIe siècle avec sa vue panoramique, et les plages de Pampelonne à Ramatuelle où les clubs de plage vous accueillent en toute exclusivité.\n\nNous recommandons la formule journée complète (8h) pour profiter pleinement de Saint-Tropez et de ses environs : Ramatuelle, Gassin et leurs vignobles, les Plages de l'Escalet sauvages et préservées.`,
    highlights: ["Plages de Pampelonne", "La Place des Lices & son marché", "Le Port et ses yachts", "La Citadelle de Saint-Tropez", "Ramatuelle & Gassin", "Village de Grimaud", "Les plages de l'Escalet"],
    tips: ["Juillet-août : circulation difficile — partez tôt le matin (8h)", "Le marché de la Place des Lices se tient mardi et samedi matin", "Ramatuelle vaut le détour pour sa vue et ses vignobles"],
    bestTime: "Mai–Juin et Septembre",
    metaTitle: "Excursion Saint-Tropez depuis Nice avec chauffeur privé | Riviora",
    metaDescription: "Excursion Saint-Tropez & Ramatuelle en voiture privée depuis Nice ou Cannes. Plages de Pampelonne, port, village. Dès 350€. Riviora.",
    keywords: ["excursion Saint-Tropez", "VTC Saint-Tropez", "chauffeur privé Saint-Tropez", "visite Saint-Tropez", "transfert Nice Saint-Tropez"],
    lat: 43.2677,
    lng: 6.6402,
  },
  {
    slug: "cannes",
    name: "Cannes & La Croisette",
    country: "France",
    region: "Alpes-Maritimes",
    duration: "35 min de Nice",
    price: "100",
    priceLabel: "À partir de 100€",
    heroImage: "https://images.unsplash.com/photo-1562883676-8c7feb83f09b?auto=format&fit=crop&w=1920&q=85",
    description: "La Croisette, le Festival, les Îles de Lérins et le charme authentique du Suquet.",
    longDescription: `Cannes, ville de cinéma et d'élégance, offre bien plus que son célèbre Festival. La Croisette, boulevard mythique bordé de palaces et de plages privées, invite à la flânerie et au glamour. Le vieux quartier du Suquet, avec ses ruelles et son panorama exceptionnel sur la baie, révèle l'âme provençale de la cité.\n\nDes Îles de Lérins — Sainte-Marguerite et son fort où fut emprisonné le Masque de Fer, et Saint-Honorat et son monastère millénaire — aux marchés colorés de Forville, Cannes surprend à chaque détour. Votre chauffeur Riviora vous y conduit confortablement, vous laissant libre de profiter sans contrainte.\n\nNous proposons également des excursions combinées Cannes + Antibes ou Cannes + Mougins (village des peintres) pour une journée riche et variée sur la Côte d'Azur.`,
    highlights: ["La Croisette & ses palaces", "Le Palais des Festivals", "Le quartier du Suquet", "Le marché Forville", "Île Sainte-Marguerite (Le Masque de Fer)", "Île Saint-Honorat & son monastère", "Mougins village des peintres"],
    tips: ["L'Île Sainte-Marguerite se fait en ferry depuis le Vieux-Port (15 min)", "Le marché Forville est ouvert tous les matins sauf lundi", "Mougins à 10 min — village-musée incontournable"],
    bestTime: "Toute l'année · Évitez le Festival (mi-mai)",
    metaTitle: "Excursion Cannes & Croisette en voiture privée depuis Nice | Riviora",
    metaDescription: "Transfert et excursion Cannes depuis Nice avec chauffeur privé VTC. La Croisette, Îles de Lérins, marché Forville. Dès 100€. Riviora.",
    keywords: ["excursion Cannes", "VTC Cannes", "transfert Nice Cannes", "chauffeur privé Cannes", "visite Cannes Croisette"],
    lat: 43.5528,
    lng: 7.0174,
  },
  {
    slug: "eze",
    name: "Èze Village",
    country: "France",
    region: "Alpes-Maritimes",
    duration: "20 min de Nice",
    price: "120",
    priceLabel: "À partir de 120€",
    heroImage: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?auto=format&fit=crop&w=1920&q=85",
    description: "Village médiéval perché à 427m dominant la Méditerranée. Vue à couper le souffle.",
    longDescription: `Èze est l'un des plus beaux villages perchés de France. Juché à 427 mètres d'altitude sur un promontoire rocheux, ce village médiéval offre une vue panoramique extraordinaire sur la Méditerranée, de la Riviera française jusqu'aux côtes italiennes par temps clair.\n\nLes ruelles pavées d'Èze, bordées de bougainvillées et de boutiques d'artisans, mènent jusqu'au Jardin Exotique qui couronne le sommet du village — un chef-d'œuvre botanique perché sur les ruines d'un ancien château. La Parfumerie Fragonard, dont l'usine historique se trouve au pied du village, propose des visites gratuites passionnantes.\n\nNietzsche, qui fréquentait le sentier qui porte aujourd'hui son nom, trouva à Èze l'inspiration pour "Ainsi parlait Zarathoustra". Votre chauffeur Riviora vous dépose au cœur du village (accessible en voiture) et vous attend le temps de votre exploration.`,
    highlights: ["Jardin Exotique au sommet (vue 360°)", "Ruelles médiévales pavées", "Parfumerie Fragonard (visite gratuite)", "Sentier Nietzsche (descente vers Eze-sur-Mer)", "Panorama Monaco & Méditerranée", "Artisans et galeries d'art", "Château en ruines"],
    tips: ["Arrivez avant 10h pour éviter les cars de touristes", "La descente par le Sentier Nietzsche prend 1h30 — prévoir des chaussures confortables", "Fragonard offre une visite de l'usine gratuite en bas du village"],
    bestTime: "Toute l'année · Printemps et automne idéaux",
    metaTitle: "Excursion Èze Village depuis Nice avec chauffeur | Riviora",
    metaDescription: "Excursion Èze Village perché en voiture privée depuis Nice. Jardin Exotique, vue Méditerranée, Fragonard. 20 min. Dès 120€. Riviora.",
    keywords: ["excursion Eze village", "VTC Eze", "chauffeur privé Eze", "visite Eze Nice", "village perché Côte d'Azur"],
    lat: 43.7268,
    lng: 7.3614,
  },
  {
    slug: "antibes",
    name: "Antibes & Cap d'Antibes",
    country: "France",
    region: "Alpes-Maritimes",
    duration: "25 min de Nice",
    price: "90",
    priceLabel: "À partir de 90€",
    heroImage: "https://images.unsplash.com/photo-1503917988258-f87a78e3c995?auto=format&fit=crop&w=1920&q=85",
    description: "L'authenticité de la Côte d'Azur : remparts, Picasso, marché provençal et plages dorées.",
    longDescription: `Antibes, cité antique fondée par les Grecs il y a 2500 ans, est l'une des villes les plus authentiques de la Côte d'Azur. Ses remparts vauban plongent directement dans la Méditerranée, créant l'un des panoramas les plus photographiés de la région.\n\nLe Musée Picasso, installé dans le château Grimaldi où l'artiste travailla en 1946, abrite une collection exceptionnelle. Le marché Provençal, couvert sous ses arcades, déborde de couleurs et de parfums du mardi au dimanche. Juan-les-Pins, station balnéaire animée, offre des plages de sable doré et une vie nocturne légendaire.\n\nLe Cap d'Antibes, presqu'île exclusive abritant les villas des plus grandes fortunes mondiales, offre un sentier du littoral magnifique à parcourir à pied. Votre chauffeur vous dépose et vous récupère selon votre rythme.`,
    highlights: ["Musée Picasso (Château Grimaldi)", "Remparts vauban & vue mer", "Marché Provençal couvert", "Juan-les-Pins & ses plages", "Sentier du Littoral du Cap d'Antibes", "Port Vauban (plus grand port de Méditerranée)", "Vieille ville & ses ruelles"],
    tips: ["Le sentier du littoral (Cap d'Antibes) fait 5 km — comptez 2h", "Marché Provençal : mardi au dimanche matin", "Juan-les-Pins pour la baignade : plages à 5 min du centre"],
    bestTime: "Mai–Octobre",
    metaTitle: "Excursion Antibes & Cap d'Antibes depuis Nice | Riviora",
    metaDescription: "Excursion Antibes avec chauffeur privé. Musée Picasso, remparts, marché, Juan-les-Pins. 25 min de Nice. Dès 90€. Riviora VTC.",
    keywords: ["excursion Antibes", "VTC Antibes", "chauffeur Antibes", "visite Antibes Nice", "Cap d'Antibes excursion"],
    lat: 43.5804,
    lng: 7.1282,
  },
  {
    slug: "grasse",
    name: "Grasse",
    country: "France",
    region: "Alpes-Maritimes",
    duration: "45 min de Nice",
    price: "140",
    priceLabel: "À partir de 140€",
    heroImage: "https://images.unsplash.com/photo-1593118247619-e2d6f056869e?auto=format&fit=crop&w=1920&q=85",
    description: "Capitale mondiale du parfum. Fragonard, Molinard, Galimard et la Haute-Provence.",
    longDescription: `Grasse, classée au Patrimoine Mondial de l'UNESCO pour son savoir-faire en matière de parfumerie, est la capitale mondiale des parfums depuis le XVIIe siècle. Nichée à 400 mètres d'altitude dans l'arrière-pays azuréen, cette ville authentique offre un contraste saisissant avec le littoral animé.\n\nTrois maisons de parfum historiques se partagent la ville : Fragonard (la plus célèbre et la plus accessible), Molinard et Galimard. Toutes proposent des visites gratuites de leurs usines et des ateliers de création de parfum sur réservation — une expérience unique à vivre en famille ou en couple.\n\nLa vieille ville de Grasse, avec ses escaliers en colimaçon, ses placettes ombragées et son marché aux fleurs, mérite une exploration pédestre d'au moins une heure. Le Musée International de la Parfumerie raconte 3000 ans d'histoire olfactive avec des collections remarquables.`,
    highlights: ["Parfumerie Fragonard (visite gratuite)", "Parfumerie Molinard", "Parfumerie Galimard", "Musée International de la Parfumerie", "Vieille ville & ses escaliers", "Marché de Grasse", "Atelier création de parfum"],
    tips: ["Réservez l'atelier parfum à l'avance (Fragonard ou Galimard)", "La visite usine Fragonard est entièrement gratuite", "Combinez avec Mougins (15 min) pour une journée complète"],
    bestTime: "Mai–Juin (floraison de la rose) · Toute l'année",
    metaTitle: "Excursion Grasse Parfumerie depuis Nice | Chauffeur Riviora",
    metaDescription: "Excursion Grasse capitale du parfum avec chauffeur privé depuis Nice. Fragonard, Molinard, Galimard. Visite usine gratuite. Dès 140€.",
    keywords: ["excursion Grasse", "visite parfumerie Grasse", "chauffeur Grasse Nice", "Fragonard visite", "VTC Grasse"],
    lat: 43.6593,
    lng: 6.9232,
  },
  {
    slug: "gorges-du-verdon",
    name: "Gorges du Verdon",
    country: "France",
    region: "Alpes-de-Haute-Provence",
    duration: "1h45 de Nice",
    price: "550",
    priceLabel: "À partir de 550€",
    heroImage: "https://images.unsplash.com/photo-1502126324834-38f8e02d7160?auto=format&fit=crop&w=1920&q=85",
    description: "Le Grand Canyon européen. Falaises turquoise, lac de Sainte-Croix et villages provençaux.",
    longDescription: `Les Gorges du Verdon, surnommées le "Grand Canyon européen", constituent l'un des sites naturels les plus spectaculaires d'Europe. Le canyon de 25 kilomètres, creusé jusqu'à 700 mètres de profondeur par la rivière Verdon aux eaux d'un turquoise irréel, offre des panoramas à couper le souffle depuis les routes de corniche.\n\nLe lac de Sainte-Croix, à l'embouchure des gorges, offre une plage de galets et des eaux turquoise où la baignade et le canoë sont possibles d'avril à octobre. Le village de Moustiers-Sainte-Marie, classé parmi les "Plus Beaux Villages de France", domine la vallée avec son étoile suspendue entre deux falaises — une légende vieille de 700 ans.\n\nLa journée complète est indispensable pour apprécier ce territoire exceptionnel. Votre chauffeur Riviora connaît les meilleurs points de vue et arrêts photos, évitant les itinéraires balisés pour les cars de touristes.`,
    highlights: ["Belvédère de la Mescla (vue vertigineuse)", "Point Sublime & la Couloir Samson", "Lac de Sainte-Croix (baignade)", "Moustiers-Sainte-Marie (Plus Beau Village)", "Route de Corniche Sublime", "Village de Castellane", "Balcon du Verdon"],
    tips: ["Prévoir impérativement la journée complète (départ 8h)", "Le lac de Sainte-Croix : emportez maillot et chaussures eau", "Moustiers : arrivée avant 11h pour le marché"],
    bestTime: "Mai–Septembre · Baignade juin–août",
    metaTitle: "Excursion Gorges du Verdon depuis Nice | Chauffeur privé Riviora",
    metaDescription: "Excursion journée aux Gorges du Verdon depuis Nice avec chauffeur. Lac de Sainte-Croix, Moustiers. Grand Canyon européen. Dès 550€.",
    keywords: ["excursion Gorges du Verdon", "visite Verdon Nice", "chauffeur Gorges Verdon", "lac Sainte-Croix excursion", "Moustiers-Sainte-Marie"],
    lat: 43.7459,
    lng: 6.3468,
  },
  {
    slug: "milan",
    name: "Milan (Milano)",
    country: "Italie",
    region: "Lombardie",
    duration: "3h30 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1513581166391-887a96ddeafd?auto=format&fit=crop&w=1920&q=85",
    description: "La capitale de la mode et du design, à 3h30 de Nice en voiture privée premium.",
    longDescription: `Milan, capitale économique et culturelle de l'Italie, est accessible en voiture privée depuis Nice en environ 3h30, en traversant la Riviera italienne et la plaine du Pô. Riviora assure ce transfert international en Mercedes Classe V avec chauffeur bilingue franco-italien.\n\nLa ville de la Scala, du Duomo et de la Galleria Vittorio Emanuele II — la plus ancienne galerie marchande d'Italie — mérite amplement le déplacement. Le quartier de Brera et ses galeries d'art, Navigli et ses canaux animés, le Quadrilatère de la Mode avec ses boutiques de luxe : Milan offre une richesse culturelle et gastronomique exceptionnelle.\n\nNous proposons ce trajet en aller-retour journalier ou en transfert simple (idéal pour les connexions depuis l'aéroport de Milan Malpensa ou Linate). Devis personnalisé selon la date et le nombre de passagers.`,
    highlights: ["Le Duomo di Milano", "Galleria Vittorio Emanuele II", "La Scala (opéra)", "Quartier de Brera", "Navigli (canaux)", "Quadrilatère de la Mode", "La Cène de Léonard de Vinci (sur réservation)"],
    tips: ["La Cène de Léonard (Santa Maria delle Grazie) se réserve 2 mois à l'avance", "Privilégiez la traversée de nuit ou le départ à 6h pour éviter les bouchons à l'entrée de Milan", "Combinez avec un arrêt à Gênes pour le déjeuner"],
    bestTime: "Avril–Juin et Septembre–Novembre",
    metaTitle: "Transfert Nice → Milan (Milano) en voiture privée | Riviora",
    metaDescription: "Transfert Nice Milan en chauffeur privé. 3h30, Mercedes Classe V. Devis gratuit. Riviora assure vos trajets internationaux sur la Riviera.",
    keywords: ["transfert Nice Milan", "VTC Nice Milano", "chauffeur privé Milan Nice", "trajet Nice Milan voiture", "transport Nice Italie"],
    lat: 45.4642,
    lng: 9.19,
  },
  {
    slug: "portofino",
    name: "Portofino",
    country: "Italie",
    region: "Ligurie",
    duration: "2h30 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1523906834658-6e24ef2386f9?auto=format&fit=crop&w=1920&q=85",
    description: "Le village le plus glamour d'Italie, à 2h30 de Nice via la Riviera italienne.",
    longDescription: `Portofino, minuscule village de pêcheurs devenu symbole du luxe à l'italienne, fait partie des destinations les plus exclusives de la Méditerranée. Ses maisons colorées reflétées dans les eaux calmes du port, entourées de végétation luxuriante, forment l'un des tableaux les plus photographiés au monde.\n\nDepuis Nice, votre chauffeur Riviora vous conduit via l'Autoroute des Fleurs — un trajet spectaculaire longeant la Riviera italienne, passant par Menton, la frontière, Vintimille, San Remo et Gênes. L'arrivée à Portofino, depuis la route en corniche, est un moment magique.\n\nPortofino se mérite : pas de voitures en centre-village, accès par petite route. Riviora vous dépose au parking de Santa Margherita Ligure (15 min à pied) ou au passage bateaux selon la saison. Le temps libre sur place vous permettra de profiter des boutiques, des restaurants de fruits de mer et des plages de la presqu'île.`,
    highlights: ["Le port de Portofino & ses maisons colorées", "Église San Giorgio (vue panoramique)", "Plage de Paraggi (eau cristalline)", "Santa Margherita Ligure", "Abbaye de San Fruttuoso (en bateau)", "Promenade de la presqu'île", "Restaurant Ristorante Puny (réservation conseillée)"],
    tips: ["Réservez le restaurant à l'avance — Portofino est très demandé en été", "Louez un bateau sur place pour voir la côte depuis la mer", "Santa Margherita Ligure offre hébergement à moindre coût"],
    bestTime: "Mai–Juin et Septembre · Évitez août (surpeuplement)",
    metaTitle: "Excursion Portofino depuis Nice avec chauffeur privé | Riviora",
    metaDescription: "Excursion Portofino en voiture privée depuis Nice. 2h30 via Riviera italienne. Village de pêcheurs mythique. Devis gratuit Riviora.",
    keywords: ["excursion Portofino Nice", "transfert Nice Portofino", "chauffeur Portofino", "VTC Nice Italie", "Portofino voiture privée"],
    lat: 44.3029,
    lng: 9.2095,
  },
  {
    slug: "cinque-terre",
    name: "Cinque Terre",
    country: "Italie",
    region: "Ligurie",
    duration: "2h45 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=1920&q=85",
    description: "Cinq villages accrochés aux falaises de Ligurie — un des sites UNESCO les plus beaux d'Italie.",
    longDescription: `Les Cinque Terre — Riomaggiore, Manarola, Corniglia, Vernazza et Monterosso — sont cinq villages de pêcheurs accrochés aux falaises escarpées de Ligurie, classés au Patrimoine Mondial de l'UNESCO. Leurs maisons colorées, leurs vignobles en terrasse et leurs ruelles tortueuses forment l'un des paysages les plus extraordinaires d'Italie.\n\nDepuis Nice, Riviora vous conduit en 2h45 environ jusqu'à La Spezia ou directement au pied des villages accessibles en voiture (Monterosso et Riomaggiore). Un guide-chauffeur expérimenté vous conseillera sur le meilleur village à visiter selon la saison et vos envies.\n\nNous recommandons la formule journée complète : arrivée matinale à Vernazza (le plus photographié), déjeuner à Manarola, promenade de la Via dell'Amore entre Riomaggiore et Manarola, et retour en soirée. Les bateaux inter-villages complètent parfaitement la visite en saison.`,
    highlights: ["Vernazza (le plus pittoresque)", "Manarola & le coucher de soleil", "Via dell'Amore (Riomaggiore–Manarola)", "Monterosso & sa plage", "Corniglia (accès 382 marches)", "Vignobles en terrasse", "Bateau inter-villages (été)"],
    tips: ["Achetez la Cinque Terre Card pour les sentiers et les bateaux", "Évitez juillet-août — préférez mai-juin ou septembre", "Vernazza pour déjeuner, Manarola pour le coucher de soleil"],
    bestTime: "Mai–Juin et Septembre · Octobre pour les vendanges",
    metaTitle: "Excursion Cinque Terre depuis Nice avec chauffeur | Riviora",
    metaDescription: "Excursion Cinque Terre en voiture privée depuis Nice. 5 villages UNESCO en Ligurie. Journée complète. Devis sur demande. Riviora.",
    keywords: ["excursion Cinque Terre Nice", "transfert Nice Cinque Terre", "VTC Cinque Terre", "chauffeur Cinque Terre", "visite Cinque Terre voiture"],
    lat: 44.1265,
    lng: 9.7117,
  },
  {
    slug: "geneve",
    name: "Genève",
    country: "Suisse",
    region: "Canton de Genève",
    duration: "3h00 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1560969184-10fe8719e047?auto=format&fit=crop&w=1920&q=85",
    description: "La cité internationale sur le Léman, ses montres et son Jet d'Eau iconique, à 3h de Nice.",
    longDescription: `Genève, ville cosmopolite au bord du lac Léman, est l'une des destinations les plus élégantes d'Europe. Capital des organisations internationales (ONU, Croix-Rouge, CERN), elle allie diplomatie, horlogerie de prestige et qualité de vie exceptionnelle.\n\nRiviora assure ce trajet international Nice–Genève en confort absolu à bord de votre Mercedes Classe V. La traversée par les Alpes offre des paysages à couper le souffle entre Nice et Digne-les-Bains, puis la route des Alpes jusqu'au Léman.\n\nÀ Genève, le Jet d'Eau (140 mètres de hauteur), la Vieille-Ville avec la Cathédrale Saint-Pierre, le quartier des boutiques horlogères de la Rue du Rhône, et les rives du Léman constituent les incontournables. Ce trajet est particulièrement prisé pour les connexions vers l'aéroport de Genève-Cointrin ou les stations de ski des Alpes suisses.`,
    highlights: ["Jet d'Eau de Genève (140m)", "Vieille-Ville & Cathédrale Saint-Pierre", "Rue du Rhône (horlogerie)", "Lac Léman & ses quais", "CERN (visite sur réservation)", "Quartier des Nations (ONU)", "Palais des Nations"],
    tips: ["Prévoyez votre carte d'identité ou passeport (passage frontière)", "L'aéroport de Genève est à 20 min du centre", "Les boutiques ferment souvent le dimanche"],
    bestTime: "Toute l'année · Printemps et été pour le lac",
    metaTitle: "Transfert Nice → Genève en voiture privée | Riviora",
    metaDescription: "Transfert Nice Genève en chauffeur privé. 3h de trajet, Mercedes premium. Connexion aéroport Cointrin. Devis gratuit. Riviora.",
    keywords: ["transfert Nice Genève", "VTC Nice Genève", "chauffeur privé Genève Nice", "Nice Genève voiture", "transport Nice Suisse"],
    lat: 46.2044,
    lng: 6.1432,
  },
  {
    slug: "courchevel",
    name: "Courchevel",
    country: "France",
    region: "Savoie, Alpes",
    duration: "3h15 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&w=1920&q=85",
    description: "La station de ski la plus prestigieuse des Alpes, à 3h15 de Nice avec votre chauffeur.",
    longDescription: `Courchevel, station la plus renommée des Trois Vallées et de l'ensemble du domaine skiable mondial, accueille chaque hiver les plus grandes fortunes et célébrités du globe. Courchevel 1850, son Altiport légendaire et ses palaces aux pieds des pistes incarnent l'excellence du tourisme alpin de luxe.\n\nRiviora assure le transfert Nice–Courchevel en Mercedes Classe V (équipée de pneus neige et chaînes en hiver), en combinant confort de route et sécurité en montagne. Le trajet traverse Gap, Grenoble et la Tarentaise — des paysages alpins grandioses.\n\nNous recommandons le départ à 7h depuis Nice pour une arrivée sur les pistes avant 11h. Ce transfert est particulièrement demandé en période de vacances scolaires et lors des grandes semaines de ski en janvier-mars. Réservation anticipée fortement conseillée.`,
    highlights: ["Domaine des Trois Vallées (600 km de pistes)", "Courchevel 1850 & ses palaces", "L'Altiport de Courchevel (spectaculaire)", "La Croisette & ses commerces", "Pistes noires La Face & Jockeys", "Restaurants étoilés en altitude", "Courchevel Village (authentique)"],
    tips: ["Réservez 4-6 semaines à l'avance en haute saison (Noël, février)", "Équipements neige systématiques de novembre à avril", "Courchevel 1550 est moins chère et tout aussi bien reliée"],
    bestTime: "Décembre–Mars (ski) · Juillet–Août (randonnée, VTT)",
    metaTitle: "Transfert Nice → Courchevel en voiture privée | Riviora",
    metaDescription: "Transfert Nice Courchevel avec chauffeur privé. 3h15. Véhicule équipé neige. Station de ski 1850. Devis gratuit. Riviora.",
    keywords: ["transfert Nice Courchevel", "VTC Nice Courchevel", "chauffeur ski Courchevel", "Nice Courchevel voiture", "transport ski Alpes Nice"],
    lat: 45.4163,
    lng: 6.6347,
  },
  {
    slug: "megeve",
    name: "Mégève",
    country: "France",
    region: "Haute-Savoie, Alpes",
    duration: "3h00 de Nice",
    price: "0",
    priceLabel: "Sur demande",
    heroImage: "https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=1920&q=85",
    description: "Le village alpin le plus chic de France, à 3h de Nice. Charme authentique et domaine ski exceptionnel.",
    longDescription: `Mégève, créée par la Baronne Noémie de Rothschild au début du XXe siècle comme alternative à Saint-Moritz, est restée fidèle à son esprit d'élégance discret et authentique. Son centre piéton avec ses chalets centenaires, ses boutiques de luxe et ses restaurants gastronomiques en font une station unique, à l'âme préservée malgré sa réputation mondiale.\n\nContrairement à Courchevel, Mégève a conservé son caractère de village savoyard avec ses ruelles pavées et son église du XVIIe siècle. Le Palais des Sports, les patinoires, et les 445 km de pistes du domaine du Mont-Blanc en font une destination 4 saisons.\n\nLe trajet Nice–Mégève en voiture privée (environ 3h) passe par Grenoble et Sallanches. Riviora assure ce transfert avec véhicule équipé pour les conditions hivernales. Service de bagages à ski disponible sur demande.`,
    highlights: ["Village piéton & ses chalets", "Domaine du Mont-Blanc (445 km)", "Vue sur le Mont-Blanc", "Patinoire en plein air (hiver)", "Marché hebdomadaire (samedi)", "Restaurants étoilés Flocons de Sel & Kintessence", "Golf 18 trous (été)"],
    tips: ["Mégève est plus accessibles en voiture que Courchevel", "Le samedi matin : marché du village incontournable", "Réservez les restaurants étoilés plusieurs semaines à l'avance"],
    bestTime: "Décembre–Mars (ski) · Juin–Septembre (randonnée, golf)",
    metaTitle: "Transfert Nice → Mégève en voiture privée | Riviora",
    metaDescription: "Transfert Nice Mégève avec chauffeur privé. 3h, Mercedes équipé neige. Station chic du Mont-Blanc. Devis gratuit. Riviora.",
    keywords: ["transfert Nice Mégève", "VTC Nice Megeve", "chauffeur Mégève Nice", "Nice Mégève voiture ski", "transport ski Haute-Savoie"],
    lat: 45.8574,
    lng: 6.6161,
  },
];

export function getDestinationBySlug(slug: string): Destination | undefined {
  return destinations.find((d) => d.slug === slug);
}
